### ISSUE TITLE
Issue with changing base stats

### ISSUE THREAD

**Issue by thejvu** [svfeplvce/ProjectSky#11]
Seems like this only applies to Greninja, but whenever I edit its base stats, the ingame Greninja becomes a normal type with horrendously low stats (in the 40s at level 36). The app itself also causes several Greninja sprites to appear right after Arceus and before Victini on the overall list of pokemon. Is there in issue regarding the fact that there are three variants of Greninja (regular with torrent and protean, pre transformation battle bond, and post transformation battle bond)? The one I'm trying to edit is the regular variant without battle bond.

https://imgur.com/a/VHsEubu

The examples shown have Greninja with typically unavailable moves and Magic Guard as its ability, but that was changed prior with PkHex. I had a Dragonite with Aerialate made in PkHex prior as well, but it was able to safely have its base stats changed with Sky unlike Greninja

**Comment by svfeplvce** [comment]
im gonna push something out here in a second, try using it and see if that fixes the issue

**Comment by svfeplvce** [comment]
[ProjectSky_1.1.3.zip](https://github.com/svfeplvce/ProjectSky/files/11082969/ProjectSky_1.1.3.zip)

**Comment by thejvu** [comment]
Looks like that did the trick. Thanks a bunch mate
