### ISSUE TITLE
Am I able to use this to edit things in other mods like Pokemon SV+?

### ISSUE THREAD

**Issue by Shinyuusha** [svfeplvce/ProjectSky#12]
I just want to know how I would I go about editing a mod. Like pick up where they left off and make my own edits. Or am I just doomed to start from scratch unless I have the files the original modder used?

**Comment by Shinyuusha** [comment]
I want to use a pokearray file from an already exisiting mod but I don't know where to place so project sky reads those edits instead. It only reads from where I left off when I initially opened to start fresh edits. Can you help me here?

**Comment by svfeplvce** [comment]
you have to deserialise the files you want to use yourself using flatc and put them inside the output path you set when you first open up the program
