### ISSUE TITLE
Selection Box Issue

### ISSUE THREAD

**Issue by SneezyWeavile** [svfeplvce/ProjectSky#14]
Clicking the selection box in the gray area inside the blue border does nothing, but clicking the blue border area works correctly.
![Screenshot (1)](https://github.com/svfeplvce/ProjectSky/assets/103162491/575e370e-685b-4b45-9fff-a4ca4208cb73)

**Comment by svfeplvce** [comment]
ah yeah this is an issue ive found with the selection boxes. gonna leave this open while i find a fix.

**Comment by svfeplvce** [comment]
figured it out, pushing out a fix with 2.0.3.2
