### ISSUE TITLE
making my own edits from another .json file

### ISSUE THREAD

**Issue by Shinyuusha** [svfeplvce/ProjectSky#16]
"you have to deserialise the files you want to use yourself using flatc and put them inside the output path you set when you first open up the program" 

Okay, I have a personal_array.fbs file. I was able to get a .json file but the program always spits out its own and won't work when I rename the one it makes. Do I need a fresh personal_array.bin or can I not use the one this program generates? I open the .json file sky makes, I can read everything perfectly, yet my json is all mixed up and chaotic to say the least...what am I doing wrong here?

**Comment by svfeplvce** [comment]
when did you get your fbs file because its been updated since dlc came out.

**Comment by svfeplvce** [comment]
closing since i got no reply and i assume you figured it out
