### ISSUE TITLE
No zip and "process already in use" error

### ISSUE THREAD

**Issue by RobinsonBradley** [svfeplvce/ProjectSky#6]
I have 2 problems:
1. I don't get a zip file in my output folder when exiting the program.
2. After editing a pokémon I get the error that the flatc.exe process can't be executed because it's already in use.

It once generated a zip file, even with the error but now it just doesn't generate one anymore. Tried reinstalling and deleting config.json.

[Error.txt](https://github.com/svfeplvce/ProjectSky/files/10387641/Error.txt)

**Comment by svfeplvce** [comment]
okay hey so can you share the steps you took from loading the program to the time of the error so i can try and replicate it? thanks!

**Comment by svfeplvce** [comment]
update: try using 1.0.5 and see if it still happens

**Comment by RobinsonBradley** [comment]
So my steps are:
1. Extract the program from the zip
2. Make an output folder
3. Open the Sky.exe executable
4. Designate the output folder when prompted
5. Open pokémon editor
6. Edit a pokémon
7. Press the back button at the top left corner
8. "flatc.exe can't be executed because it's already in use"
9. Close the pokemon editor and then closing the program
10. No zip in the Output folder just the bare files

I don't know what i'm doing wrong, one day it worked then it just stopped working.

Attached a gif for ease.
![Error](https://user-images.githubusercontent.com/42919095/211851775-abd95d80-f86a-4da0-9746-4851ee942003.gif)

**Comment by svfeplvce** [comment]
thats.. weird. let me see if i can replicate it.

**Comment by RobinsonBradley** [comment]
Ok, an update. I tried it on my school laptop and it worked ... The first time. It creates a zip without the "process is already in use" error but when I want to edit some more it just gives me the error and the zip isn't updated.

**Comment by RobinsonBradley** [comment]
2nd Update, I asked a friend to use the program and it just works. I don't know why but could it be that my antivirus is just not allowing the executable to function properly?

**Comment by RobinsonBradley** [comment]
Ok last update, found the solution. Just disable Norton, great antivirus except when it's not. Welp thanks for the nice program, and sorry for bothering you.

**Comment by svfeplvce** [comment]
oh well its great that you found the error! ill pin this so anyone who has this issue knows the solution :)
