### ISSUE TITLE
ISSUE STILL PERSISTS. "System.ArgumentNullException: Value cannot be null. (Parameter 'stream')"

### ISSUE THREAD

**Issue by Kreygasm13** [svfeplvce/ProjectSky#7]
[log.txt](https://github.com/svfeplvce/ProjectSky/files/10405291/log.txt)

Sorry to interrupt again but... Error is still persisting with me using 1.0.5

I seriously don't know why this happens anymore.

**Comment by svfeplvce** [comment]
okay yeah so this time around i have no idea what could possibly be causing it because the steps i used to replicate it last time arent working.

**Comment by svfeplvce** [comment]
okay, idea:
delete the projectsky folder COMPLETELY and do a complete and fresh reinstall.

**Comment by Kreygasm13** [comment]
> okay, idea: delete the projectsky folder COMPLETELY and do a complete and fresh reinstall.

I already did fresh Install numerous times...

Because Also I didnt name my folder ProjectSky... I am assuming its an another folder...

Where is that folder located exactly?

**Comment by svfeplvce** [comment]
just whatever folder the exe is in.

**Comment by Kreygasm13** [comment]
> just whatever folder the exe is in.

Already did that... I deleted its file over and over again.

and Reinstalled it already. ( I am not lying ) But I am still not sure WHY this happens.

I guess I will have to either request it or do it manually...
