### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by AshleyZX** [svfeplvce/ProjectSky#8]
[log.txt](https://github.com/svfeplvce/ProjectSky/files/10421565/log.txt)

The exe opens just fine and can see all the pokemons, but I get this error when i try to change the held item of wild pokemons and also the X is a 9 and the back arrow is a |  for some reason.

Already installed NET 7.0 (SDK), got the new Project Sky 1.0.6 and did a fresh installation, but it just won't work.

It seems it works just fine for others, but I don't know what else to try.

**Comment by svfeplvce** [comment]
the second issue is known, the only fix as of now is to install the font "dripicons-v2".

as for the first issue, let me see whats going on and if i can help

**Comment by svfeplvce** [comment]
fixed in 1.0.6-2
