### ISSUE TITLE
Checking Eevee evolutions transformed all its forms into eevees

### ISSUE THREAD

**Issue by AshleyZX** [svfeplvce/ProjectSky#9]
Checking Eevee's evolutions window transformed all its forms into Eevees and had to do a fresh install.

There was an error window, but no log and can't redo the error to send a screenshot. (my bad)

Version 1.0.6-2

**Comment by svfeplvce** [comment]
okay i will update soon

**Comment by svfeplvce** [comment]
sorry it took me over a month to update, i THINK i fixed it. let me check.

**Comment by svfeplvce** [comment]
fixed in 1.0.7

**Comment by AshleyZX** [comment]
Thanks for all the hard work!  :D
